version: '3.7'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=burgerapi
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodata:
    driver: local